pull_request_rules:
  - name: Clean Mergify Experiment
    conditions:
      - author = musername1
    actions:
      label:
        add:
          - mergify-triggered

  - name: Edge Trigger Test
    conditions:
      - author = musername1
    actions:
      comment:
        message: "EDGE-TRIGGER-TEST"
